services:
  _defaults:
    autowire: true
    autoconfigure: true

  Netmex\Response\:
    resource: '../src/'

  Netmex\Response\EventListener\ResponseListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  Netmex\Response\Resolver\ResponseStrategyResolver:
    arguments:
      $strategies: !tagged_iterator app.response_strategy
      $defaultStrategy: '@Netmex\Response\Strategy\JsonResponseStrategy'