services:
  Netmex\Response\EventListener\ResponseListener:
    tags:
      - {
          name: kernel.event_listener,
          event: kernel.view,
          method: onKernelView,
        }
    autowire: true
    autoconfigure: false

  Netmex\Response\EventListener\ExceptionListener:
    tags:
      - {
          name: kernel.event_listener,
          event: kernel.exception,
          method: onExceptionEvent,
        }
    autowire: true
    autoconfigure: false
